version: '3.5'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shopteam
      POSTGRES_PASSWORD: 123
    volumes:
      - ./storage/init_db:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2.8-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - postgres

  opa:
    image: openpolicyagent/opa:0.12.0
    container_name: opa
    hostname: opa
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./opa:/etc/opt/opa
    command: ["run", "--server", "/etc/opt/opa/authz.rego"]

networks:
  default:
    name: shop
    driver: bridge