# dsn - parameter for connecting to the database
dsn = "postgres://shopteam:123@localhost:5432/shop?sslmode=disable"
port = ":8000"
server_url = "https://104.248.44.156"
# timeout - max time in seconds to graceful shutdown
timeout = 5
# log_level - sets the logging level (info, warning, debug, error, panic, fatal)
log_level = "debug"

fs_path = "./static/files/"

read_timeout = 50
write_timeout = 50
read_header_timeout = 50