# dsn - parameter for connecting to the database
dsn = "postgres://shopteam:123@localhost:5432/shop?sslmode=disable"
port = ":8000"
server_url = "https://104.248.44.156"
# timeout - max time in seconds to graceful shutdown
timeout = 5
# log_level - sets the logging level (info, warning, debug, error, panic, fatal)
log_level = "debug"

fs_path = "./storage/files/"

# amazon rds
host_amazon = "cozydragon-instance.c421xe1df6ut.ap-south-1.rds.amazonaws.com"
port_amazon = "5432"
username_amazon = "DBconnect"
password_amazon = "qwerty12345"
dbname_amazon = "cozydragonDB"